config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :surveys, only: [:index, :show]
  get 'message', to: 'messages#handle', as: 'handle'

  root to: 'surveys#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :survey

  validates :survey, :number, :text, presence: true
  validates :number, uniqueness: { scope: :survey, message: 'is unique per survey' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :name, :number, presence: true, uniqueness: true
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :answers

  validates :name, :question, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def handle
    data = params[:Body].gsub(/\D/, ' ').split
    survey_id = data.first.to_i
    answer_number = data.last.to_i

    if survey_id > 0 && answer_number > 0
      message = "You voted in Survey #{survey_id} for Answer #{answer_number}!"
      ActionCable.server.broadcast("surveys:#{survey_id}", {vote: answer_number})
    else
      message = 'Try again with both survey and answer number!'
    end

    render plain: message
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
    @phone = Phone.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableDemo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/index.html.erb
<div id='container'>
  <h2>Take a survey!</h2>

  <% @surveys.each do |survey| %>
    <h4><%= link_to survey.name, survey_path(survey) %></h4>
  <% end %>
</div>

app/views/surveys/show.html.erb
<div id='container'>
  <%= link_to 'Home', surveys_path %>

  <h2>Survey #<%= @survey.id %>: <%= @survey.name %></h2>

  <ul>
    <% @survey.answers.each do |answer| %>
      <li>Answer #<strong><%= answer.number %></strong>: <%= answer.text %></li>
    <% end %>
  </ul>

  <h3>Text "Survey <%= @survey.id %>: (number of your answer)" to <%= @phone.number %></h3>
</div>

<%= react_component('Results', {
  survey_id: @survey.id,
  answers: @survey.answers.map { |a| {number: a.number, text: a.text} }
}) %>